### ISSUE TITLE
How it works

### ISSUE THREAD

**Issue by craigfrancis** [Danack/RfcLiteralString#3]
With commit [a739bd2](https://github.com/Danack/php-src/commit/a739bd296d61c54c1eceaff843e414f2ab8d5f43); I appreciate this isn't complete, but I'm impressed how small you've managed to get it.

If I'm reading it correctly (I'm a little out of my depth with C), you're adding a flag to say if a variable is a literal.

And there is a new [`ZVAL_COPY_VALUE_LITERAL`](https://github.com/Danack/php-src/blob/a739bd296d61c54c1eceaff843e414f2ab8d5f43/Zend/zend_types.h#L1243) function, that's similar to [`ZVAL_COPY_VALUE`](https://github.com/Danack/php-src/blob/a739bd296d61c54c1eceaff843e414f2ab8d5f43/Zend/zend_types.h#L1234).

This new function is used by [`zend_ast_create_zval_int`](https://github.com/Danack/php-src/blob/a739bd296d61c54c1eceaff843e414f2ab8d5f43/Zend/zend_ast.c#L59).

But I'm not sure what it's doing.

Is this when the AST (Abstract Syntax Tree) is being built, and the literals are being parsed by that process?

For comparison, I was considering trying to trim down the [taint extension](https://github.com/laruence/taint), so it ignored all escaping functions, and didn't touch functions like `explode()`.

**Comment by Danack** [comment]
> If I'm reading it correctly (I'm a little out of my depth with C), you're adding a flag to say if a variable is a literal.

Yes. There's a few flags for different stuff and appears to be a spare bit at least.

> But I'm not sure what it's doing.

Me neither.

> Is this when the AST (Abstract Syntax Tree) is being built, and the literals are being parsed by that process?

I think it's at a later stage, after the AST has been built, and it is then being used to actually create the individual zval for this invocation of the script. 

i.e. the source code is compiled once to the AST, and then separately when the code is run, that's when the in-memory variables actually get created.

**Comment by craigfrancis** [comment]
Thanks looking into this, and explaining.

Just as a note to self; we had a discussion in Room 11 ([start](https://chat.stackoverflow.com/transcript/message/51564002#51564002)), where NikiC suggested using [GC flags on the string](https://chat.stackoverflow.com/transcript/message/51565348#51565348).

**Comment by craigfrancis** [comment]
Hi Dan, just wondered if you got my email about funding / development costs, sent on the 10th Feb to basereality.com (don't know if that's a spam dumping ground). Not sure if you would be interested, or had other commitments, there's no pressure.
