### ISSUE TITLE
Concatenation, and performance concerns

### ISSUE THREAD

**Issue by craigfrancis** [Danack/RfcLiteralString#5]
I would really like to support concatenation, especially as I have used it in a few thousand times in my systems (that is, concatenating safe literals for use in SQL or HTML snippets).

But, if the performance concerns are too great, and it's likely to cause the RFC to fail, using a string/query builder isn't the end of the world - especially as many developers are sensible and use something to abstract database queries (I'm often working with big-ish tables, so the queries often need tweaking).

One minor loss would be for the libraries themselves. While they can do the `is_literal()` check as they receive the values, they probably wouldn't be able to use this function internally (e.g. for an ORM to be sure the final SQL they create was made from safe literals).

The same with the core PHP functions; in the far and distant future, it would be nice if `$pdo->query()`, `mysqli_query()`, `echo`, `exec()`, etc could use this (and depending on an ini setting, do nothing, create a notice, raise an exception, etc). But that's unlikely to work if they can't take concatenated strings.

**Comment by Danack** [comment]
I was going to give a longer answer that goes into depth about how it would be a bad tradeoff.....but instead, how about having a function in PHP core of `function implode_literal_strings(string $glue, array $strings): string`

That takes an array of strings, checks they are all literal ones, and then combines them, and sets the appropriate flag.....

That solves your use-case, without any worry about performance hit.

**Comment by craigfrancis** [comment]
I like it.

So anyone writing PHP wouldn't do string concatenating, they would instead build up an array of strings, in the same way that SQL has an array of parameters.

Minor query - I'm not sure it needs to have a `$glue` variable, as while I can think of one use case (building up a WHERE clause that will be joined together with `AND`, `OR`, etc), I suspect that most of the time it won't be used. So it might be possible to simplify to `function concat_literal_strings(array $strings): string` (I'd be happy with either though).

**Comment by Danack** [comment]
Functions are really cheap, and making stuff easy to use is worth implementing them.

Actually, probably need both `function literal_implode(string $glue, array $strings): string` and `function literal_combine(string $piece, string ...$pieces): string`, so that you can combine either an array, or:

literal_combine($foo, '=', $bar);

As having to chuck stuff into an array would be annoying.

**Comment by craigfrancis** [comment]
If PHP Internals would be fine with that, then yes, absolutely, and I probably would use all 3.

**Comment by craigfrancis** [comment]
Just to note, most developers won't need this.

For example, Doctrine, when using [QueryBuilder](https://www.doctrine-project.org/projects/doctrine-orm/en/2.8/reference/query-builder.html#high-level-api-methods), the `->where($predicates)` method, which can take a string (dangerous), it's usually something small/simple like `'u.archived = "false"'`, where it should never be mixed with external/user-supplied values (that's what `setParameter()` is for).

---

And as a note to self, to show how this could work with SQL, with a very simple WHERE clause, using the PHP 7.4 spread operator, and the $db wrapper taking the `$sql` array to check and implode:

Before:
```php
$where_sql = '
    u.type = ? AND
    u.archived = "false"';

$parameters = [];
$parameters[] = $user_type;

if ($user_limit !== NULL) {

    $where_sql .= ' AND
        u.id = ?';

    $parameters[] = $user_limit;

}

$sql = 'SELECT
            u.id,
            u.name
        FROM
            ' . TABLE_PREFIX . 'user AS u
        WHERE
            ' . $where_sql . '
        ORDER BY
            name';

foreach ($db->fetch_all($sql, $parameters) as $row) {
}
```
After:
```php
$where_sql = ['
    u.type = ? AND
    u.archived = "false"'];

$parameters = [];
$parameters[] = $user_type;

if ($user_limit !== NULL) {

    $where_sql[] = ' AND
        u.id = ?';

    $parameters[] = $user_limit;

}

$sql = ['SELECT
            u.id,
            u.name
        FROM
            ', TABLE_PREFIX, 'user AS u
        WHERE
            ', ...$where_sql, '
        ORDER BY
            name'];

foreach ($db->fetch_all($sql, $parameters) as $row) {
}
```
Just one tiny irritation, the 'S' in SELECT is no longer aligned with the other keywords :-P

Or, if using these functions directly:
```php
$where_sql = [];
$where_sql[] = 'u.type = ?';
$where_sql[] = 'u.archived = "false"';

$parameters = [];
$parameters[] = $user_type;

if ($user_limit !== NULL) {

    $where_sql[] = 'u.id = ?';

    $parameters[] = $user_limit;

}

$sql = literal_concat(['
        SELECT
            u.id,
            u.name
        FROM
            ', TABLE_PREFIX, 'user AS u
        WHERE
            ', literal_implode(' AND ', $where_sql), '
        ORDER BY
            name']);

foreach ($db->fetch_all($sql, $parameters) as $row) {
}
```

**Comment by Danack** [comment]
> Just to note, most developers won't need this.

Yeah. But they should be there to avoid anyone from emailing internals saying "You haven't considered my use-case so this RFC is terrible and everyone should vote against it." aka removing the reasonable position that it [isn't complete](https://github.com/Danack/RfcCodex/blob/master/rfc_attitudes.md#being-obviously-incomplete).

**Comment by craigfrancis** [comment]
Not for now... 

If we do re-visit string concatenation, [@krakjoe has noted](https://chat.stackoverflow.com/transcript/message/51968102#51968102) that we'd be looking at "ZEND_CONCAT, ZEND_FAST_CONCAT, and the ROPE handlers", which would not be pretty; but "in theory you could output specialised opcodes and not interfere with the original ones" (might help address some of the perf issues?).

But extensions are likely to be a big issue - they "exchange strings with userland, they're not obliged to use the zend_string api - the input could be all literals but the output won't be".

**Comment by Danack** [comment]
So, we're happy to drop raw concatenation?

I think that's actually the correct choice, and wrote some words about why it makes maintaining apps easier: https://github.com/Danack/RfcLiteralString/blob/master/rfc_words.md#why-no-support-for-string-concatenation-operator

>  Just one tiny irritation, the 'S' in SELECT is no longer aligned with the other keywords

I think the whole alignment of any arrays is annoying.

```
foo(
    'bar',
    [
        'this',
        'is',
        'terrible' 
    ]
);
```


```
foo(
    'bar',
    [  'this',
        'is',
        'worse' ]
);
```


```
foo(
    'bar', [
        'this',
        'is',
        'worster'
    ]
);
```

**Comment by craigfrancis** [comment]
It's really up to you.

Joe did an experimental version just looking at concatenation (to roughly see what kind of performance impact it would have), and Máté Kocsis is currently testing it (most of Máté's work is really to get a testing system setup for PHP in general, so is likely to be a few more days before we see any results).

I've done my own very primitive test, using 2 compiled versions of PHP (with vs without patch), running a [very basic test](https://github.com/craigfrancis/php-is-literal-rfc/blob/main/tests/001.phpt) that simply ran `$x = $a . 'b' . $c . 1 . " [$a $b]";` 5 million times per run (worst case scenario, as most systems are doing a lot more than concat), where I did 8 alternating runs (4 each), discarding the first 2 runs (warm up), adding the remaining 3 runs together, then re-doing them at 7 different times of the day (hopefully avoiding other background tasks on my computer), then sorting them:

    for F in a b a b a b a b; do echo -n $F; TEST=1 ./src/$F/sapi/cli/php ./tests/001.phpt; done

    1.354s to 1.364s = +0.010s = 0.74%
    1.354s to 1.367s = +0.013s = 0.96%
    1.354s to 1.367s = +0.013s = 0.96%
    1.355s to 1.368s = +0.013s = 0.96%
    1.354s to 1.368s = +0.014s = 1.03%
    1.357s to 1.374s = +0.017s = 1.25%
    1.341s to 1.358s = +0.017s = 1.27%

I'm hoping the actual affect will be less for normal systems, as I'm pretty sure they will be doing a lot more than concat... but I also don't know how Internals will view this.

Joe has suggested that Dmitry would be best to do a proper test, and might be able to make suggestions.

Technically ORM's don't really need concat, as most of their methods take short/simple strings. But there will be people out there that prefer to write SQL (guilty), and that would nearly always use string concat today, so it would make it a bit easier for them if concat was supported. But as you say, a string builder object, or using `literal_implode()` or `literal_combine()` functions, isn't the end of the world.

And yes, the aesthetics of arrays, yeah, I tend to go with your first example, and try to get used to it.

**Comment by Danack** [comment]
I _think_ (with a confidence of about 70%) that forcing people to use the literal_combine() and literal_implode() functions is the better choice for large applications, with the reasoning as per: https://github.com/Danack/RfcLiteralString/blob/master/rfc_words.md#why-no-support-for-string-concatenation-operator

When there's not as many typos and incorrect code in the rfc doc, I might ask Christoph K for his opinion.

And that's probably regardless of the performance. maybe.

**Comment by craigfrancis** [comment]
tbh, I'm not sure either.

You really do have a point, it would allow you to identify the mistake at the point it happens.

And if Máté does find performance issues that can't be easily addressed, I think that's a done deal.

The only reason I'm still hesitating, is because I know I've used a lot of string concat, and I suspect there will be lots of other projects in a similar position, and while I will be able to change them, it will take a while (and for my own sanity, I think I'd need to alias `literal_combine()` to a `c()` function).

**Comment by craigfrancis** [comment]
While I'm waiting for the detailed results from Máté, the "the difference seem to be around ~1% in Laravel over the course of 3 different measurements", so I think that's it.

And yes, there might be tweaks that can improve its performance, but I think that's for later (e.g. there was clear input from users that this would really be useful).

If anything comes up, I'll re-open this, but let's just assume string concat isn't going to happen.
