### ISSUE TITLE
HTML Snippets Example

### ISSUE THREAD

**Issue by craigfrancis** [Danack/RfcLiteralString#7]
With your [`esprinf()`](https://github.com/Danack/esprintf), I really like its simplicity, it's very clear about which escaping approach to use.

My [html-template](https://github.com/craigfrancis/php-is-literal-rfc/blob/main/examples/html-snippets-1.php?ts=4) approach is similar, but a little excessive - In debug/development mode it will check that it's valid XML (ensures attributes are quoted, and has good nesting, while still being valid for normal HTML5), and it checks safe values are being applied to the HTML template (i.e. stopping `javascript:...` being added to an `a[href]`). The non-debug mode is a single/quick `preg_split()`.

Both could use `is_literal()` to stop mistakes such as:

```php
    $string = "<span class=':attr_class'>:html_message</span>";
```

Being accidentally edited to:

```php
    $string = "<span class=':attr_class' data-name='$name'>:html_message</span>";
```

And while yours won't automatically detect and block `class=:html_class`, it's very fast, it will make anyone using it be aware of the escaping process, and it's easy(ish) to spot mistakes for anyone reviewing the code.

**Comment by Danack** [comment]
> And while yours won't automatically detect and block class=:html_class

I'm thinking of adding that, but will probably leave it until after this RFC is done.

btw there is an example of using is_literal in the https://github.com/danack/esprintf/tree/is_literal_support branch, to force people to either use a literal string, or a previous escaped string.

But as there is nothing to do for this repo in this issue, going to close this issue.

**Comment by craigfrancis** [comment]
That's a nice example for making sure the $template can be trusted.
