### ISSUE TITLE
test literalness isn't preserved.

### ISSUE THREAD

**Issue by Danack** [Danack/RfcLiteralString#9]
There's possibly some function in core that clones a string, then appends to it.....need to check that doesn't preserve the literal flag.

**Comment by craigfrancis** [comment]
Do you have a test case?

---

Not sure, but Joe was doing stuff with these two concat functions in `zend_vm_def.h`, which can append data to a string:

    ZEND_VM_HANDLER(8, ZEND_CONCAT

    ZEND_VM_COLD_CONSTCONST_HANDLER(53, ZEND_FAST_CONCAT

Where I broke my bodge job version, where `$literal = 'a'; $literal .= time();` incorrectly preserved the flag.

With the const/strings bit at the start, there are 4 parts... the first two is when one of the strings has a length of 0 (I think it's kinda doing nothing)... the third, I think is the important bit, and uses `zend_string_extend()`... the fourth I think is when it creates a new string entirely.

I'm not really sure on the differences between `ZEND_CONCAT` and `ZEND_FAST_CONCAT`.

And there is also the "rope" stuff (`56, ZEND_ROPE_END`), which I think is when you have variables in a double quoted string, e.g. "Hi $name, today is $day".

**Comment by Danack** [comment]
> Do you have a test case?

Not yet. not sure if there is even a function that does it in core. Just thought of it and made an issue to avoid forgetting.

**Comment by Danack** [comment]
Joe said he couldn't think of any example in core.

It's entirely possible for extensions to do that, probably. But extensions can affect safety in myriad other ways, so I don't think it is of concern, and I don't plan to mention it in the RFC.
